const sendForgotPasswordRequest = async (username) => {
  try {
    // Generate OTP logic here
    const otp = generateOTP();

    const response = await fetch('http://localhost:5000/forgotpassword', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ username }),
    });
    const data = await response.json();
    console.log('Forgot password request sent:', data);

    // Call the function to send the reset password request
    sendResetPasswordRequest(username, otp);
  } catch (error) {
    console.error('Error sending forgot password request:', error);
  }
};

const sendResetPasswordRequest = async (username, otp, newPassword) => {
  try {
    const response = await fetch('http://localhost:5000/resetpassword', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ username, otp, newPassword }),
    });
    const data = await response.json();
    console.log('Reset password request sent:', data);
  } catch (error) {
    console.error('Error sending reset password request:', error);
  }
};

// Replace with the relevant values for testing
const username = 'poorank123'; // Replace with the username of the user
const password = 'password123'; // Replace with the password entered by the user
const otp = generateOTP(); // Replace with the OTP generated by your OTP generation logic
const newPassword = 'NewP@ssw0rd'; // Replace with the new password entered by the user

// Send forgot password request
sendForgotPasswordRequest(username);

// Send reset password request
sendResetPasswordRequest(username, otp, newPassword);
